invoicer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('user/', include('custom_users.urls')),
    path('invoice/', include('invoice.urls'))
]

logger/urls.py
from django.urls import path
urlpatterns = [
    path('', views.index)
]

invoice/models.py
from django.db import models
from django.core.validators import RegexValidator
# Create your models here.
from custom_users.models import UUIDModel

class WorkOrder(models.Model):
    class StatusTypes(models.TextChoices):
        NOT_ASSIGNED = 'N'
        ASSIGNED = 'A'
        UNDER_REVIEW = 'U'
    
    order_title = models.CharField(max_length=64)
    order_descript = models.CharField(max_length=254)
    vendor = models.ForeignKey('custom_users.Vendor', on_delete=models.CASCADE, related_name='vendor')
    completion_date = models.DateField(null=True, auto_now=False, auto_now_add=False)
    job_site = models.ForeignKey('invoice.JobSite', on_delete=models.CASCADE)
    status = models.CharField(choices=StatusTypes, default='N', max_length=1)

    def __str__(self):
        return f'{self.order_title}'


class Invoice(UUIDModel):
    uuid = models.CharField(blank=True, null=False, max_length=16)
    invoice_title = models.CharField(blank=False, max_length=64)
    invoice_descript = models.CharField( max_length=254)
    customer = models.ForeignKey( 'custom_users.Customer', blank=True, null=True, on_delete=models.CASCADE, related_name='recipient')
    issuer = models.ForeignKey("custom_users.UserContactInfo", on_delete=models.CASCADE, related_name='issuer')
    issued_at = models.DateField(auto_now_add=False, editable=True)
    deadline = models.DateField()
    status = models.CharField(default='PENDING', max_length=16)
    work_order = models.ForeignKey(WorkOrder, blank=False, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(uuid_size=16, *args, **kwargs)

    
class JobSite(models.Model):
    address = models.ForeignKey('custom_users.Address', on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    

class WorkItem(models.Model):
    validate_money = RegexValidator(regex='[0-9]+\.[0-9]{2}', message='Format must be in 00.00')

    cost = models.FloatField(default=0.00, validators=[validate_money], blank=False)
    memo = models.CharField(null=True, max_length=64)
    descript = models.CharField(null=True, max_length=254)
    work_order = models.ForeignKey(WorkOrder, on_delete=models.CASCADE)
    

    
class InvoiceAttachment(models.Model):
    upload_file = models.FileField(upload_to="invoice_attachments/%Y/%m/%d/")
    # ffile = models.OneToOneField(FileMeta, on_delete=models.CASCADE)
    # uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)
    # title = models.CharField(max_length=64)
    # descript = models.CharField(max_length=255, blank=True)
    # path = models.CharField(max_length=64)
    # status = models.CharField(max_length=16)
    # work_order = models.OneToOneField(WorkOrder, on_delete=models.CASCADE, primary_key=True)

'''
SELECT a.invoice_title, iw.order_title, a.issued_at, a.deadline, b.total from invoice_invoice as a
   JOIN invoice_workorder as iw on iw.id = a.work_order_id
   JOIN (SELECT SUM(cost) as total, work_order_id from invoice_workitem) as b
   on iw.id = b.work_order_id
   WHERE iw.vendor_id = 1;


Select a.invoice_title, a.issued_at, a.deadline, b.total from invoice_invoice 
JOIN invoice_workorder on invoice_workorder.id = a.work_order_id
JOIN 
(SELECT SUM(cost) as total, work_order_id from invoice_workitem
    JOIN invoice_workorder on invoice_workorder.id = invoice_workitem.work_order_id
    GROUP BY invoice_workitem.work_order_id) as b
;
'''

invoicer/views.py
from django.shortcuts import render


def index(request):
    template_name= 'invoicer/index.html'
    if not request.htmx:
        print('request.htmx not found... returning complete')
        template_name= 'invoicer/base.html'
    return render(request, template_name, {})

invoicer/templates/invoicer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
   
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    
    {% load static %}
    <script src='{% static "invoicer/js/htmx.min.js" %}' defer></script>

    <link preload rel='stylesheet' href="{% static "invoicer/css/globals.css" %}" />
    {% block title %}
        <title>Invoice Manager</title>
    {% endblock title %}
    {% block nav %}
        {% include "invoicer/nav.html" %}
    {% endblock nav %}
</head>
<body>
    {% block content %}
        <div id='main'>
            {% include partial_template_name|default:"invoicer/index.html" %}
        </div>
    {% endblock content %}
    
</body>
</html>

invoicer/templates/invoicer/form.html
{% block form %}
{% load crispy_forms_tags %}
    <form class='form-block-pb sm-pd-pb' action='' method='POST'>
        {% csrf_token %}
        <table>
            {% for f in form %}
                {% for field in f %}
                    <div class="form_field_wrapper">
                        {{ field|as_crispy_field }}
                        
                    </div>
                {% endfor %}
                {% if f.non_field_errors %}
                    <ul class='alert'>
                    {% for errors in f.non_field_errors %}
                        <li style='list-style: none; margin: 0; padding: 0;'>
                        {{ errors }}
                        </li>
                    {% endfor %}
                    </ul>
                {% endif %}
            {% endfor %}
            </table>
           
        <button class='btn btn-primary' tabindex='0' type='submit'>{{btn_display|default_if_none:'Submit'}}</button>
    </form>
{% endblock form %}

invoicer/templates/invoicer/formset copy.html
{% load crispy_forms_tags %}
<h2> Create New Invoice </h2>
<form id='form_container' method='POST'>
    {% csrf_token %}
    
    {{ work_item_form.management_form }}

        <section class='card sm-pd-pb sm-mg-bottom-pb'>
            <h3>Invoice Details</h3>
            {{ invoice_form.invoice_title|as_crispy_field }}
            {{ invoice_form.invoice_descript|as_crispy_field }}
            {{ invoice_form.issued_at|as_crispy_field }}
            {{ invoice_form.deadline|as_crispy_field }}
            {{ invoice_form.work_order|as_crispy_field }}
        </section>
        <section id='customer-section' class='card sm-pd-pb sm-mg-bottom-pb'>
            <h3>Customer Selection</h3>
            <ul class='nav nav-tabs' id='pills-tab' role='tablist'>
                <li class='nav_item' role='presentation'>
                    <button class='nav-link activate' id='pills-exist' data-bs-toggle="tab" data-bs-target="#select_customer" type="button" role="tab" aria-controls="select_customer" aria-selected="true">Select Customer</button>
                </li>
                <li class='nav_item' role='presentation'>
                    <button class='nav-link activate' id='pills-create' data-bs-toggle="tab" data-bs-target="#create_customer" type="button" role="tab" aria-controls="create_customer" aria-selected="false">Create Customer</button>
                </li>
            </ul>
            <div id='customer-tab' class='tab-content'>
                <input type='hidden' value="{{active_tab|escape}}" id='active_tab'/>
                <div class='tab-pane active' role='tabpanel' aria-labelledby='pills-exist' id='select_customer'> 
                    <span>Choose a pre-existing customer as the recipient.</span>
                    {{ invoice_form.customer|as_crispy_field }}
                </div>

                <div class='tab-pane' role='tabpanel' aria-labelledby='pills-create' id='create_customer' >
                    <span>Create and assign a customer to this invoice.</span>

                    {% for field in customer %}
                        {{ field|as_crispy_field }}
                    {% endfor %}
                    {% for field in customer_addr_form %}
                        {{field|as_crispy_field}}
                    {% endfor %}

                    {% for field in customer_email_form %}
                        {{field|as_crispy_field}}
                    {% endfor %}

                    {% for field in customer_phone_form %}
                        {{field|as_crispy_field}}
                    {% endfor %}
                </div>

            </div>
        </section>

        <section id='item_container' class='card sm-pd-pb sm-mg-bottom-pb'>
            <div>
                {% for form in work_item_form %}
                    <h3 name='item_header'>Item #{{forloop.counter}}</h3>
                    {{ form|crispy }}
                {% endfor %}
            </div>
            <button id='add_item_btn' type='button' disabled>Add New Item</button> 
        </section>

    <button id='submit_btn' type='submit'>Submit</button> 
</form>

<div id='empty_work_items' style='display: none;'>
    <div>
    <h3 name='item_header'>Item #_</h3>
        {{ work_item_form.empty_form|crispy }}
    <div>
</div>
<!--  ########################################################################################### -->
<div id='empty_form_order' style='display: none;'>
    
</div>

<script>
    
    $(document).ready(function() {

        $('#id_invoice_order-work_order').select2({});
        $('#id_invoice_order-customer').select2({});

        var active_tab = $('#active_tab').val()
        console.log(active_tab)
        if (active_tab == 'select_customer'){
            $('#create_customer').fadeOut(0, function() {
                $('#create_customer select, input, textarea').prop('disabled', true); // Disable fields
                $('#select_customer').fadeIn(0, function() {
                    $('#select_customer select, input, textarea').prop('disabled', false); // Enable fields
                });
                $('#active_tab').val('select_customer')
            });    
        }
        else {
            $('#select_customer').fadeOut(0, function() {
                $('#select_customer select, input, textarea').prop('disabled', true); // Disable fields
                $('#create_customer').fadeIn(0, function() {
                    $('#create_customer select, input, textarea').prop('disabled', false); // Enable fields
                });
                $('#active_tab').val('create_customer')
            });
        }
        
        function swapFieldsStatus(container, status=null){
            const children = container.querySelectorAll('input, select, textarea')
            children.forEach(child => {
                if (status === null){
                    child.disabled = !child.disabled
                }
                else{
                    child.disabled = status;
                }
                
            })   
        }

        $('#pills-exist').on('click', function() {
            $('#create_customer').fadeOut(0, function() {
                $('#create_customer select, input, textarea').prop('disabled', true); // Disable fields
                $('#select_customer').fadeIn(0, function() {
                    $('#select_customer select, input, textarea').prop('disabled', false); // Enable fields
                });
                $('#active_tab').val('select_customer')
            });
        });
        
        $('#pills-create').on('click', function() {
            $('#select_customer').fadeOut(0, function() {
                $('#select_customer select, input, textarea').prop('disabled', true); // Disable fields
                $('#create_customer').fadeIn(0, function() {
                    $('#create_customer select, input, textarea').prop('disabled', false); // Enable fields
                });
                $('#active_tab').val('create_customer')
            });
        });
        

    });
    
    document.addEventListener("DOMContentLoaded", (event) => {
        var triggerTabList = [].slice.call(document.querySelectorAll('#pills-tab button'))
        triggerTabList.forEach(function (triggerEl) {
          var tabTrigger = new bootstrap.Tab(triggerEl)
        
          triggerEl.addEventListener('click', function (event) {
            event.preventDefault()
            tabTrigger.show()
          })
        })

        var triggerEl = document.querySelector('#pills-tab li:first-child button');
        if (triggerEl !== null)
            bootstrap.Tab.getInstance(triggerEl).show() // Select first tab
    
    
        var select_customer = document.getElementById('pills-exist')
        var create_customer = document.getElementById('pills-create')
        
        var select_container = document.getElementById('select_customer')
        var create_container = document.getElementById('create_customer')

        console.log('DOM loaded...')

        
    })
    let add_btn = document.getElementById('add_item_btn')
    let item_container = document.getElementById('item_container')   
    let form = document.getElementById('form_container')
    

    let item_tracker = document.getElementById('id_item-TOTAL_FORMS')
    
    let regex = /__prefix__/g
    add_btn.addEventListener('click', addItem)
    function allowAddItem(e){
        
        if (e.target.value !== ''){
            add_btn.disabled = false
        }
        else{
            add_btn.disabled = true
        }
    }

  
    function addItem(e){
        let item_clone = document.getElementById('empty_work_items').firstElementChild.cloneNode(true)
        count = parseInt(item_tracker.value)
        item_clone.querySelector('h3[name = "item_header"]').textContent = `Item #${count + 1}`
    
        item_clone.innerHTML = item_clone.innerHTML.replace(regex, `${count - 1}`)
        item_tracker.value = `${count + 1}`
        item_container.insertBefore(item_clone, add_btn)
    }

</script>

invoicer/templates/invoicer/formset.html
<form id='work_order_container' method='POST'>
    {% csrf_token %}
    {{ form.management_form }}


    {% for order in form %}
    <div class='work_order'>

        <h2 id='work_order-0-header'>Work Order #1</h2>
        <table>
        {{ order.as_table }}
        </table>
    </div>
    {% endfor %}
  
    <button class='btn btn-primary' type='button' id='add_work_btn'>Add</button>
    <button class='btn btn-primary' type='submit'>Submit</button>

</form>

<script>
    // for delete...
    // let form_id_list = new Set([1]);
    // let freed_id_list = new Set([]);

    let addButton = document.getElementById("add_work_btn")
    let numOfForms = {{form.total_form_count}} 
    var totalFormEl = document.querySelector("#id_work_order-TOTAL_FORMS")
    let formEl = document.getElementsByClassName('work_order')[0]
    let container = document.getElementById('work_order_container')

    addButton.addEventListener('click', addOrder)

    function addOrder(e){
        e.preventDefault()

        let formCopyEl = formEl.cloneNode(true)
        
 
        const regex = /work_order-([0-9])+-/gm;
        let text = formCopyEl.innerHTML
        text = text.replace(regex, `work_order-${numOfForms}-`)

        numOfForms += 1

        formCopyEl.innerHTML = text;

        totalFormEl.value = `${numOfForms}`
        container.insertBefore(formCopyEl, addButton)
        document.getElementById(`work_order-${numOfForms - 1}-header`).innerHTML = `Work Order #${numOfForms}`

    }
</script>

invoicer/templates/invoicer/index.html
<h1>
    Welcome Home!
</h1>
<p>placeholder</p>

invoicer/templates/invoicer/nav.html
<nav class='navbar navbar-light navbar-expand-sm' style='background-color: #e3f2fd;'>
    <div class='container-fluid'>
        {% block navItems %}
            <a tabindex='0' class='navbar-brand' hx-get='/' hx-target='#main' hx-swap='innerHTML' hx-push-url='/'>Home</a>
            <a tabindex='0' class='navbar-brand' hx-get='/' hx-target='#main' hx-swap='innerHTML' hx-push-url='/'>About</a>
            {% if user.is_authenticated %}
                <a tabindex='0' class='navbar-brand' hx-get='/invoice/' hx-target='#main' hx-swap='innerHTML' hx-push-url='/invoice'>Invoices</a>
                <a tabindex='0' class='navbar-brand' hx-get='/' hx-target='#main' hx-swap='innerHTML' hx-push-url='/'>{{user.username}}</a>
                {% comment "placeholder here" %}{% endcomment %}
                <a tabindex='0' class='navbar-brand' href='{% url 'logout' %}'>Logout</a>    
            {% else %}
                <a tabindex='0' class='navbar-brand' hx-get='/user/login/' hx-target='#main' hx-swap='innerHTML' hx-push-url='/user/login/'>Sign In</a>    
            {% endif %}
        {% endblock navItems %}
    </div>
</nav>